required_directories:
  - proj5_code/segmentation
  - proj5_code/proj5_unit_tests/segmentation
  - Camvid
  - camvid_dataset_lists
required_files:
  - pyproject.toml
  - camvid_download_dataset.sh
optional_directories:
  - additional_data
optional_files:
  - README.txt